language: java
jdk:
   - oraclejdk8

addons:
   apt:
      packages:
         - oracle-java9-installer

install: true

before_script:
   - export PATH=$M2_HOME/bin:$PATH
   - remove_dir_from_path $JAVA_HOME/bin
   - export JAVA_HOME=/usr/lib/jvm/java-9-oracle
   - export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH
   - export MAVEN_SKIP_RC="true"

script:
   - mvn compile

deploy:
   provider: script
   script: mvn deploy -Dmaven.test.skip -s settings.xml
   skip_cleanup: true
   on:
      branch: develop