language: java
jdk:
   - oraclejdk8

branches:
   except:
      - feature/jigsaw

deploy:
   provider: script
   script: mvn deploy -Dmaven.test.skip -s settings.xml
   skip_cleanup: true
   on:
      branch: develop