language: java
jdk:
   - oraclejdk8

addons:
   apt:
      packages:
         - oracle-java9-installer

before_install:
   - remove_dir_from_path $JAVA_HOME/bin
   - export JAVA_HOME=/usr/lib/jvm/java-9-oracle
   - export PATH=$JAVA_HOME/bin:$PATH

deploy:
   provider: script
   script: mvn deploy -Dmaven.test.skip -s settings.xml
   skip_cleanup: true
   on:
      branch: develop